CREATE OR REPLACE FUNCTION delete_patient(ids VARCHAR)
RETURNS VOID AS $$

DECLARE 
	Tid int;
		
BEGIN
	SELECT ID INTO Tid FROM PATIENT WHERE PATIENTID = ids;
	RAISE NOTICE 'PATIENT "%" SELECTED', Tid;
	
	DELETE
	FROM PACKAGEDRUGINFOTMP
	WHERE PACKAGEDDRUG IN (
		SELECT ID FROM PACKAGEDDRUGS
		WHERE PARENTPACKAGE IN (
			SELECT ID FROM PACKAGE
			WHERE PRESCRIPTION IN 
				(SELECT ID 
				FROM PRESCRIPTION 
				WHERE PATIENT = Tid)
			)
		);
	RAISE NOTICE 'PACKAGEDRUGINFOTMP deleted';

	DELETE 
	FROM PACKAGEDDRUGS
	WHERE PARENTPACKAGE IN (
		SELECT ID FROM PACKAGE
		WHERE PRESCRIPTION IN 
			(SELECT ID 
			FROM PRESCRIPTION 
			WHERE PATIENT = Tid)
		);
	RAISE NOTICE 'PACKAGEDDRUGS deleted';

	DELETE 
	FROM PRESCRIBEDDRUGS
		WHERE PRESCRIPTION IN 	
			(SELECT ID 
			FROM PRESCRIPTION 
			WHERE PATIENT = Tid
		);
	RAISE NOTICE 'PRESCRIBEDDRUGS deleted';

	DELETE
	FROM ACCUMULATEDDRUGS
	WHERE PILLCOUNT IN (
		SELECT ID FROM PILLCOUNT
		WHERE PREVIOUSPACKAGE IN (
			SELECT ID
			FROM PACKAGE WHERE PRESCRIPTION IN (
				SELECT ID 
				FROM PRESCRIPTION 
				WHERE PATIENT = Tid
			)
		)
	);
	RAISE NOTICE 'ACCUMULATEDDRUGS deleted';

	DELETE
	FROM PILLCOUNT
	WHERE PREVIOUSPACKAGE IN (
		SELECT ID FROM PACKAGE
		WHERE PRESCRIPTION IN (
			SELECT ID 
			FROM PRESCRIPTION 
			WHERE PATIENT = Tid
		)
	);
	RAISE NOTICE 'PILLCOUNT deleted';

	DELETE	
	FROM PACKAGE WHERE PRESCRIPTION IN (
		SELECT ID 
		FROM PRESCRIPTION 
		WHERE PATIENT = Tid
	);
	RAISE NOTICE 'PACKAGE deleted';
	
	DELETE 
	FROM PRESCRIPTION 
	WHERE PATIENT = Tid;
	RAISE NOTICE 'PRESCRIPTION deleted';

	DELETE 
	FROM PREGNANCY 	
	WHERE PATIENT = Tid;
	RAISE NOTICE 'PREGNANCY deleted';
	
	DELETE 
	FROM PATIENTATTRIBUTE 	
	WHERE PATIENT = Tid;
	RAISE NOTICE 'PATIENTATTRIBUTE deleted';

	DELETE 
	FROM EPISODE 
	WHERE PATIENT = Tid;
	RAISE NOTICE 'EPISODE deleted';
	
	DELETE 
	FROM APPOINTMENT 
	WHERE PATIENT = Tid;
	RAISE NOTICE 'APPOINTMENT deleted';
	
	DELETE 
	FROM ALTERNATEPATIENTIDENTIFIER 
	WHERE PATIENT = Tid;
	RAISE NOTICE 'ALTERNATEPATIENTIDENTIFIER deleted';
	
	DELETE 
	FROM PATIENT
	WHERE PATIENT.ID = Tid;
	RAISE NOTICE 'PATIENT deleted';
	
	RETURN;
END;
$$ LANGUAGE plpgsql;

-- NB: Usage  - use the String patient id
--SELECT delete_patient('ABC123');   


--DROP FUNCTION delete_patient(character varying);